// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ9WnYWgNVaqL7xiD7yWBVMpfXKTQzVdY',
    appId: '1:326691527533:web:7214c44fd85535c9ad5864',
    messagingSenderId: '326691527533',
    projectId: 'privatenotes-flutter-project-1',
    authDomain: 'privatenotes-flutter-project-1.firebaseapp.com',
    storageBucket: 'privatenotes-flutter-project-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTMv8yQNTC2iaGkFLlgN60ANHUKH_oGx4',
    appId: '1:326691527533:android:69e9d43b11632688ad5864',
    messagingSenderId: '326691527533',
    projectId: 'privatenotes-flutter-project-1',
    storageBucket: 'privatenotes-flutter-project-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWuk7jMpum2Tun64y6b0nf4D3PgUcOYPM',
    appId: '1:326691527533:ios:9c73c0db91c24572ad5864',
    messagingSenderId: '326691527533',
    projectId: 'privatenotes-flutter-project-1',
    storageBucket: 'privatenotes-flutter-project-1.appspot.com',
    iosBundleId: 'com.example.theomeFuryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWuk7jMpum2Tun64y6b0nf4D3PgUcOYPM',
    appId: '1:326691527533:ios:9c73c0db91c24572ad5864',
    messagingSenderId: '326691527533',
    projectId: 'privatenotes-flutter-project-1',
    storageBucket: 'privatenotes-flutter-project-1.appspot.com',
    iosBundleId: 'com.example.theomeFuryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ9WnYWgNVaqL7xiD7yWBVMpfXKTQzVdY',
    appId: '1:326691527533:web:622faf6712d8ca2fad5864',
    messagingSenderId: '326691527533',
    projectId: 'privatenotes-flutter-project-1',
    authDomain: 'privatenotes-flutter-project-1.firebaseapp.com',
    storageBucket: 'privatenotes-flutter-project-1.appspot.com',
  );
}
