// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjcOKgdq0_3C44Uusv8vPrdKU3i7su92w',
    appId: '1:154371143913:web:4ae22660d1fbe69f66d878',
    messagingSenderId: '154371143913',
    projectId: 'auththeome',
    authDomain: 'auththeome.firebaseapp.com',
    storageBucket: 'auththeome.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL_Hh-0w1qfKJJdMCjx800itZoFgZChOs',
    appId: '1:154371143913:android:441045535d6c553766d878',
    messagingSenderId: '154371143913',
    projectId: 'auththeome',
    storageBucket: 'auththeome.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCTQbmuwd6Uq8n-d4IXe5ndL1eHjNf3s0',
    appId: '1:154371143913:ios:034ebe309112112766d878',
    messagingSenderId: '154371143913',
    projectId: 'auththeome',
    storageBucket: 'auththeome.appspot.com',
    iosBundleId: 'com.example.theomeFuryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCTQbmuwd6Uq8n-d4IXe5ndL1eHjNf3s0',
    appId: '1:154371143913:ios:034ebe309112112766d878',
    messagingSenderId: '154371143913',
    projectId: 'auththeome',
    storageBucket: 'auththeome.appspot.com',
    iosBundleId: 'com.example.theomeFuryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjcOKgdq0_3C44Uusv8vPrdKU3i7su92w',
    appId: '1:154371143913:web:b37de59e70bfad3d66d878',
    messagingSenderId: '154371143913',
    projectId: 'auththeome',
    authDomain: 'auththeome.firebaseapp.com',
    storageBucket: 'auththeome.appspot.com',
  );

}